.TH MYSTRCAT 3 "April 2024" "v1.0" "Library Functions"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.nf
.B #include "../include/mystrfunctions.h"
.PP
.BI "int mystrcat(char *" dest ", const char *" src );
.fi
.SH DESCRIPTION
The
.B mystrcat()
function appends the
.I src
string to the
.I dest
string.
.SH RETURN VALUE
Returns the total length of the concatenated string.
.SH AUTHOR
Esha Maryam (eshamaryam11em@gmail.com)
